version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "1337:1337"
    environment:
      PORT: 1337
      REDIS_HOST: redis
      MYSQL_HOST: mysql
      MYSQL_DB: db_test
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
      FILE_PATH_TO_CHECK: /data/dummy.txt
    volumes:
      - .:/app
      - ./data/dummy.txt:/data/dummy.txt
    depends_on:
      - mysql
      - redis
    hostname: mydocker

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest

volumes:
  mysql-data:
    driver: local

